# Variables
BINARY_NAME=pokedex

# Default target to build and run the program
all: build run

# Build the Go program
build:
	go build -o $(BINARY_NAME) .

# Run the built binary
run:
	./$(BINARY_NAME)